High-level design proposal
gsagula/remote-worker pull request #3
Opened 2021-02-23 23:11 UTC by gsagula

This is a high-level design proposal which the intent is to drive some discussions around the functionalities, edge cases and mechanics of the system. 

Signed-off-by: Gabriel Linden Sagula <glindens@bitfield.org>

2021-02-24 01:03 UTC, wadells requested changes
Could you add a bit of information about how the server will keep track of currently executing/previously executing jobs? (e.g. an in memory data structure or a data store of some type)

2021-02-24 01:03 UTC, wadells commented on DESIGN.md
> +}
You may want to include the exit code if the job is in a terminal state.

2021-02-24 01:03 UTC, wadells commented on DESIGN.md
> +In order to start the server, a private key and a certificate signed by a intermediate or a root CA are required.
Isn't the CA required too?  Otherwise, how will the server validate the clients MTLS cert?  Same could be said for the client validating the server's cert.

2021-02-24 01:39 UTC, bernardjkim reviewed
Looks like a good start 👍. 
Could you include some more details on the job implementation:
- How will job id be generated?
- How will stdout/stderr be stored?
- How will process termination be handled?

2021-02-24 01:39 UTC, bernardjkim commented on DESIGN.md
> +Client can start a process by supplying a command, optional arguments and an optional time-to-live (TTL) value in seconds. If no TTL is supplied, server will use a default to reduce the chances of re
To limit scope, you do not need to implement a ttl for the jobs.

2021-02-24 02:38 UTC, knisbet commented on DESIGN.md
> +For security and performance reasons, the minimal TLS version 1.3 is used. This constraints the server and the client to only use more recent and efficient cipher suites such as [CHACHA20-POLY1305-SH
Not necessarily for the doc, but how was TLS1.3 determined to be more secure and performant than other options? On a similar note, why the chacha20 suite vs. the AES suites available in TLS1.3?

2021-02-24 03:53 UTC, gsagula commented on DESIGN.md
> +$ client start --cmd ls --args la --ttl 5
I see the problem. It will be complicated to support GNU-style command-line by separating it into `--cmd`  /  `--args`. I think an alternative is to just take the the entire command as a string,  e.g. `--cmd "grep --recursive -E '^telep' /usr/share/dict/words".

2021-02-24 04:02 UTC, gsagula commented on DESIGN.md
> +$ pid f15029dc-a251-480f-b4bf-b8739e8baaa6
It's supposed to be the output. I will get rid of the second `$`.

2021-02-24 04:04 UTC, gsagula commented on DESIGN.md
> +$ client standard -out -err
Yep, it definitely needs a ID.

2021-02-24 04:40 UTC, gsagula commented on DESIGN.md
> +This prototype consists of a server that runs a gRPC service and client. All the comunnication between the client and the sever is done securely via a mutual TLS connection. Client can only start pro
Good question! I should make it more clear. An authorised client should be able to check the status of a process independently of the state. Stop only makes sense for processes in running state, otherwise it should return an error. As per my interpretation of the original requirement, monitoring the output should be only available for processes in a running state. If we want to also stream the output of a finished process, we will need to save it somewhere.

2021-02-24 17:58 UTC, knisbet commented on DESIGN.md
> +This prototype consists of a server that runs a gRPC service and client. All the comunnication between the client and the sever is done securely via a mutual TLS connection. Client can only start pro
The L1 requirements also include the ability to just retrieve he output. If you think of something like say running `ls -l` if the output can only be retrieved while the process is running, it would be very difficult to know what the output is since `ls -l` will run and exit almost immediately.

2021-02-24 20:09 UTC, gsagula commented on DESIGN.md
> +        rpc Start(Process) returns (Error);
I was thinking to generate the id in a client using something like UUID v5 that each client can seed. However this strategy is just a unnecessary complicating factor in the whole design. The message to start the process don't actually need an id. ID should be generated by the server and returned in a start response message instead.

2021-02-24 20:57 UTC, gsagula commented on DESIGN.md
> +        rpc GetStatus(Process) returns (Status);
If the process id is invalid, status should return not found. Only ID field is required for status, all other fields will be ignored. Perhaps I could just create `StatusRequest` and `StatusResponse` messages to avoid confusion.

2021-02-24 21:35 UTC, gsagula commented on DESIGN.md
> +In order to start the server, a private key and a certificate signed by a intermediate or a root CA are required.
Ah, I have to fix this sentence but what I was trying to say is to supply a CA signed cert, where the cert is the concatenation of  the application cert, the intermediate chain if any, and the CA certificate.

2021-02-24 21:53 UTC, gsagula commented on DESIGN.md
> +message Error {
I'm not entirely sure if Error is really necessary. I was thinking in cases where the process may fail at the very early stages. For example, when the client supplies a path to a binary that does not exist. Based on earlier comments [1](https://github.com/gsagula/remote-worker/pull/3#discussion_r581505702) [2](https://github.com/gsagula/remote-worker/pull/3#discussion_r581505865), I may just rethink these messages.  Regarding the code, I just want to have a simple way to inspect the error if necessary.

2021-02-24 22:17 UTC, gsagula commented on DESIGN.md
> +Client can start a process by supplying a command, optional arguments and an optional time-to-live (TTL) value in seconds. If no TTL is supplied, server will use a default to reduce the chances of re
Right! I thought it wouldn't be to difficult to handle deadlines since the mechanism for dealing with cancellation will be already in place. I will leave it out for now but I still think it's an important feature.

2021-02-25 01:13 UTC, gsagula commented on DESIGN.md
> +For security and performance reasons, the minimal TLS version 1.3 is used. This constraints the server and the client to only use more recent and efficient cipher suites such as [CHACHA20-POLY1305-SH
I added this for two reasons: 1) reference to the subject that was made in the original requirements 2) as a novice in the subject, I want to also get some feedback based on my assumption, so here we are :)

> how was TLS1.3 determined to be more secure and performant than other options

In terms of performance, I think the most obvious aspect is the number of round-trips necessary for completing a handshake. RT has been reduced in v1.3 because the cipher suites only need to do bulk encryption and the MAC opposed to v1.2 that cipher suites need to also do RTs for key exchange and authentication. This plays in favour of security since there is no need to give away the type of key exchange / auth algorithms. Also in terms of security, many things that didn't work or the was vulnerable in previous versions have been removed in 1.3.

> chacha20 suite vs. the AES

I mentioned ChaCha20 cipher suite more as a example of a very recent suite in v1.3. However, from what I found, ChaCha has a slight advantage over AES in terms of security (theoretically). ChaCha's algorithm uses stream encryption with basic constant operations for encryption which makes it perform predictable in any hardware. AES, on the other hand, used block encryption that not only depends on the size of the block to predict the performance, but also other internal aspects of the algorithm and how it is implemented. The performance information (meaning time here) that the AES algorithm gives away and ChaCha don't, makes AES theoretically vulnerable to timing attack exploitation. To the extent of my knowledge, I think that is the main difference in terms of security between ChaCha and AES.

2021-02-25 03:15 UTC, knisbet commented on DESIGN.md
> +For security and performance reasons, the minimal TLS version 1.3 is used. This constraints the server and the client to only use more recent and efficient cipher suites such as [CHACHA20-POLY1305-SH
I think this is a pretty solid answer.

I think to simplify it, TLS1.3 is the current modern standard, and when you control both the client and the server there isn't really a good reason to support older versions, and we've already specified that TLS must be used.

For chacha20 vs AES, I think you're pretty much correct, where timing attacks might depend more on the implementation. Outside of this project though, AES is likely higher performance when run on hardware that has offload instructions, but chacha20 does have those small theoretical advantages.

What I generally recommend for this level of experience, is to use a reference like Mozilla who has a really great security team who share great parameter choices (it can be hard to pick a source, but Mozilla has a good reputation for this IMO). Since we control both client and server Modern is a great choice, where Intermediate and Old help when supporting browsers: https://wiki.mozilla.org/Security/Server_Side_TLS

2021-02-25 03:21 UTC, knisbet commented on DESIGN.md
> +message Error {
gRPC also has a separate error channel and propagation mechanism outside of the messages for a server to return an error with the status and codes packages for go to help. Very quick search for a blog to help out: https://jbrandhorst.com/post/grpc-errors/

2021-02-25 03:43 UTC, gsagula commented on DESIGN.md
> +For security and performance reasons, the minimal TLS version 1.3 is used. This constraints the server and the client to only use more recent and efficient cipher suites such as [CHACHA20-POLY1305-SH
I think I misread the last question. In terms of suit, besides my comment regarding the differences in bulk encryption, there is also the MAC portion of it which ChaCha suite combines with Poly1305 and AES with GCM. I don't know much more about the difference between both other than GCM (as AES) requires special instructions to perform, while Poly doesn't. Also, GCM has been around for a long time while Poly is newer.

2021-02-25 03:55 UTC, gsagula commented on DESIGN.md
> +For security and performance reasons, the minimal TLS version 1.3 is used. This constraints the server and the client to only use more recent and efficient cipher suites such as [CHACHA20-POLY1305-SH
I just saw you last message. Thank you for the recommendation.

2021-02-25 04:10 UTC, gsagula commented on DESIGN.md
> +message Error {
Thaks! Recommendation is very helpful. I will document the use case that I described [here](https://github.com/gsagula/remote-worker/pull/3#discussion_r582331961) and how I'm planing to handle it.

2021-03-02 02:54 UTC, bernardjkim approved these changes

2021-03-02 02:54 UTC, bernardjkim commented on DESIGN.md
> +$ client run --cacert cacert.pem --key client.key --public client.pem
Is the client meant to be run as a service? I don't think that is necessary. You can just run the commands and provide the credentials as flags.

2021-03-04 14:33 UTC, wadells approved these changes

2021-03-05 03:47 UTC, gsagula commented on DESIGN.md
> +$ client run --cacert cacert.pem --key client.key --public client.pem
Right, my bad.  It does not need to run as a server.

2021-03-08 08:01 UTC, merged